# Generated by Django 5.2.1 on 2025-05-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0003_alter_project_category_alter_review_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
